### ISSUE TITLE
Investigate ILNUMERICS - TECHNICAL COMPUTING

### ISSUE THREAD

**Issue by constructor-igor** [constructor-igor/TechSugar#224]
http://ilnumerics.net/index.html

**Comment by constructor-igor** [comment]
**Array Viewer**
![image](https://cloud.githubusercontent.com/assets/1849690/18866961/db5bc6b8-84aa-11e6-9bd7-40af9c2cdf9a.png)

![image](https://cloud.githubusercontent.com/assets/1849690/18866949/c41a67c0-84aa-11e6-9e5f-95ecaa7bafd0.png)

**Comment by constructor-igor** [comment]
expected: 
![image](https://cloud.githubusercontent.com/assets/1849690/18867502/2a72f210-84ad-11e6-9b20-78b8a2dbfb17.png)

actual:
![image](https://cloud.githubusercontent.com/assets/1849690/18867509/31f8bb50-84ad-11e6-989c-03c6e39a64b7.png)

**Comment by constructor-igor** [comment]
List ```<int> DList = new List<int>(){0, 1, 2, 3, 5, 6, 2, 4, 8, 10};``` cannot be shown.
Array ```int[][] D2 = {``` cannot be shown

**Comment by constructor-igor** [comment]
array visualizer shows same field from different objects (array)
![image](https://cloud.githubusercontent.com/assets/1849690/18868124/bc5a46b8-84af-11e6-911c-8a7f5611d8aa.png)

**Comment by hokb** [comment]
When the array descriptor is shown it takes precedance over the actual arrays dimensions. Press CTRL + ENTER to reset the current descriptor to match the actual dimensions of the array.

**Comment by hokb** [comment]
List<double> is not supported. The same as jagged arrays, as double[][]. But you can always reference a single array elements of the jagged array or use Linqs 'ToArray()'.

**Comment by constructor-igor** [comment]
**Summary**:

- Array (custom list by specific language) visualizer (basically, 2D charts).
- Fast (?) ILNumerics arrays (**it's necessary to compare with MKL**).
- Array extension (basic class) with MatLab similar syntax. 
- Wide list of UI components for data visualization (not in IDE).
- Seems, enough expensive.

**Comment by constructor-igor** [comment]
3D surface (seems, after CTRL+Enter)
![image](https://cloud.githubusercontent.com/assets/1849690/18871174/e21982e4-84bc-11e6-9498-acce79c85099.png)

**Comment by constructor-igor** [comment]
```c#
-		D3	{int[2, 5, 2]}	int[,,]
		[0, 0, 0]	1	int
		[0, 0, 1]	10	int
		[0, 1, 0]	0	int
		[0, 1, 1]	4	int
		[0, 2, 0]	-1	int
		[0, 2, 1]	2	int
		[0, 3, 0]	4	int
		[0, 3, 1]	20	int
		[0, 4, 0]	5	int
		[0, 4, 1]	100	int
		[1, 0, 0]	0	int
		[1, 0, 1]	2	int
		[1, 1, 0]	1	int
		[1, 1, 1]	2	int
		[1, 2, 0]	0	int
		[1, 2, 1]	1	int
		[1, 3, 0]	-1	int
		[1, 3, 1]	0	int
		[1, 4, 0]	2	int
		[1, 4, 1]	3	int
```

**Comment by constructor-igor** [comment]
trial period finished
