### ISSUE TITLE
Problem "Largest product in a series"

### ISSUE THREAD

**Issue by constructor-igor** [constructor-igor/TechSugar#299]
https://projecteuler.net/problem=8

> The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.
> 
> 73167176531330624919225119674426574742355349194934
> 96983520312774506326239578318016984801869478851843
> 85861560789112949495459501737958331952853208805511
> 12540698747158523863050715693290963295227443043557
> 66896648950445244523161731856403098711121722383113
> 62229893423380308135336276614282806444486645238749
> 30358907296290491560440772390713810515859307960866
> 70172427121883998797908792274921901699720888093776
> 65727333001053367881220235421809751254540594752243
> 52584907711670556013604839586446706324415722155397
> 53697817977846174064955149290862569321978468622482
> 83972241375657056057490261407972968652414535100474
> 82166370484403199890008895243450658541227588666881
> 16427171479924442928230863465674813919123162824586
> 17866458359124566529476545682848912883142607690042
> 24219022671055626321111109370544217506941658960408
> 07198403850962455444362981230987879927244284909188
> 84580156166097919133875499200524063689912560717606
> 05886116467109405077541002256983155200055935729725
> 71636269561882670428252483600823257530420752963450
> 
> Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?

**Comment by constructor-igor** [comment]
java solution
1. create maven project
```
mvn archetype:generate -DgroupId=com.mycompany.app -DartifactId=problem_0008_java -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false
```

**Comment by constructor-igor** [comment]
java: maven "Run" button disabled:
![image](https://cloud.githubusercontent.com/assets/1849690/23723729/f9554e8c-0452-11e7-9e92-264f9d7094d3.png)

**Comment by constructor-igor** [comment]
:question: 

how to re implement the code via java 8 stream?

```java
            long currentProduct = 1;
            for (int j = 0; j < numberOfDigits; j++) currentProduct *= allDigits[i + j];
```

**Comment by victor-prp** [comment]
java: maven "Run" button disabled:
You should point on specific maven phase in order to run it. For example 'test'
![maven-phase](https://cloud.githubusercontent.com/assets/1573006/23744856/8fe1d436-04be-11e7-847b-c4e10b0788b9.png)

**Comment by victor-prp** [comment]
I dont see simple and straightforward solution using streams.
Thus I would go with imperative approach in this case.
The first part (mapping from String to Digit can be easily solved with streams) as following:
    public List<Integer> toDigits(String input) {
        List<Integer> allDigits =
                Arrays.stream(input.split(""))
                        .map(Integer::decode)
                        .collect(Collectors.toList());
        
        return allDigits;

    }




Found some solution on the net: https://unamanic.blogspot.co.il/2016/10/euler-problem-8.html?view=mosaic
But again to me it is too complicated and doesn't worth it.
