### ISSUE TITLE
Project Buda.

### ISSUE THREAD

**Issue by constructor-igor** [constructor-igor/TechSugar#428]
I understand (more or less) general description.
Now, please, let's define simple short task, for example,

1. using articles from RSS from site <**define site**>
2. get from article <**define several concrete articles and expected result of analysis**>
3. how to define "**relevant**" articles (**several samples**)

So, please, could you send me path to site, path to concrete articles and expected report for the articles.
We'll make several iterations and define the short task.

References:
- https://www.kaggle.com/c/word2vec-nlp-tutorial#part-1-for-beginners-bag-of-words

**Comment by GoAlex9** [comment]
Hey sorry for the late reply. I didn't see the message until today.
I will search for examples for the tasks you mentioned above and will send you asap.

**Comment by GoAlex9** [comment]
**1.** Website example: https://www.huffingtonpost.com/
**2.** Articles: 

Positive = Good for us            Negative = Not good for us

https://www.huffingtonpost.com/entry/frenchman-trying-to-cross-atlantic-in-barrel-capsule_us_5c2641d0e4b08aaf7a8ffe93 - **Positive**

https://www.huffingtonpost.com/entry/antarctica-colin-o-brady-solo-crossing_us_5c24510fe4b05c88b6fd7546 - **Positive**

https://www.huffingtonpost.com/entry/indonesia-tsunami-death-toll-429_us_5c227dd7e4b08aaf7a8c2cb6 - **Negative**

https://www.huffingtonpost.com/entry/mexico-helicopter-crash-claims-puebla-governor-ex-governor_us_5c21a568e4b05c88b6fb84f4 - **Negative**

https://www.huffingtonpost.com/entry/egypt-ancient-tomb-discovered_us_5c15aa05e4b05d7e5d8298ef - **Positive**

https://www.huffingtonpost.com/entry/sarah-papenheim-man-arrested_us_5c0dd2f1e4b0ab8cf694a501 - **Negative**

https://www.huffingtonpost.com/entry/australia-recognizes-west-jerusalem-israels-capital_us_5c14cfbce4b05d7e5d825018 - **Debatable (maybe positive)**

https://www.huffingtonpost.com/entry/luxembourg-public-transportation_us_5c08d6ace4b069028dc685ac - **Positive**

**3.** The relevant articles are the ones mentioned above as "Positive".

- News articles that are considered as Positive news, will be the ones that we connect to the app.

**Comment by constructor-igor** [comment]
@GoAlex9 
I am going to try write simple program to download articles, make training and provide predict for new articles.

**Comment by GoAlex9** [comment]
Sounds like a  great start. Looking forward to it

**Comment by constructor-igor** [comment]
@GoAlex9 
To make training, it's necessary a big training set.
Probably, better to take prepared training set (see https://www.kaggle.com/c/word2vec-nlp-tutorial) and not create new.

I implemented a simple code to download and parse posts:
```
loaded 213 stop words and punctuation

https://www.huffingtonpost.com/entry/frenchman-trying-to-cross-atlantic-in-barrel-capsule_us_5c2641d0e4b08aaf7a8ffe93
loaded: 88 actual from 153 total words

https://www.huffingtonpost.com/entry/antarctica-colin-o-brady-solo-crossing_us_5c24510fe4b05c88b6fd7546
loaded: 157 actual from 283 total words

https://www.huffingtonpost.com/entry/indonesia-tsunami-death-toll-429_us_5c227dd7e4b08aaf7a8c2cb6
loaded: 633 actual from 1150 total words

https://www.huffingtonpost.com/entry/mexico-helicopter-crash-claims-puebla-governor-ex-governor_us_5c21a568e4b05c88b6fb84f4
loaded: 182 actual from 312 total words

https://www.huffingtonpost.com/entry/egypt-ancient-tomb-discovered_us_5c15aa05e4b05d7e5d8298ef
loaded: 322 actual from 568 total words

https://www.huffingtonpost.com/entry/sarah-papenheim-man-arrested_us_5c0dd2f1e4b0ab8cf694a501
loaded: 441 actual from 850 total words

https://www.huffingtonpost.com/entry/australia-recognizes-west-jerusalem-israels-capital_us_5c14cfbce4b05d7e5d825018
loaded: 261 actual from 484 total words

https://www.huffingtonpost.com/entry/luxembourg-public-transportation_us_5c08d6ace4b069028dc685ac
loaded: 188 actual from 330 total words
```

**Comment by GoAlex9** [comment]
So there is a system that does it. I assume they also use Python with the same method as i mentioned before. If this system won't be problematic later on for the long term, then we can use it. But if it takes us until some point and then we'll have to redo with our own codes, then I think its not a good idea. So I'm asking you whats better as i am not a technical guy :) I just generally don't like relying on other systems/software, etc. But if in our case its a better choice, then we can go for it.

from what i see the system can count the words and evaluate whether its 0 or 1 (positive or negative, or 3 - debatable. Although debatable should be a Negative response as it might be positive but might be not)

**Comment by GoAlex9** [comment]
Oh, I just realized you meant for training, not for the actual app. In that case, I guess its alright. I'm just thinking about long-term effectiveness.

**Comment by GoAlex9** [comment]
Hi Igor,

Any Progress?
